helm:
  parameters:
  - name: frontend.image.repo
    value: docker.io/74734589924/front-end
    forcestring: true
  - name: frontend.image.tag
    value: latest@sha256:ffd5a6af43d9ca7e8c19f7e8667fd896f500c6529eb2698236e784f31c798c65
    forcestring: true
