helm:
  parameters:
  - name: frontend.image.repo
    value: docker.io/74734589924/front-end
    forcestring: true
  - name: frontend.image.tag
    value: latest@sha256:f6f4e3f57b3e7889546a6a11669b4ae04d345a0d04e218fec3f7c39978296e1d
    forcestring: true
