---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
    metallb.universe.tf/address-pool: example
  labels:
    name: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 81
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
